### ISSUE TITLE
Running extinction_mag_vector raises a FileNotFoundError, caused by an issue within the dustmaps package

### ISSUE THREAD

**Issue by ahlamaq** [kemasuda/jaxstar#6]
I am following the tutorial under `examples/fitting TESS object with Teff and FeH from spectroscopy.ipynb` and encounter the following error when I run  `ak, ak_err = extinction_mag_vector(gaia['l'], gaia['b'], 1e3/parallax_obs)`:

```
File "/anaconda3/lib/python3.11/site-packages/jaxstar-0.1.0-py3.11.egg/jaxstar/utils/correction.py", line 68, in extinction_mag_vector
    bayestar = bquery(version='bayestar'+version)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/site-packages/dustmaps/bayestar.py", line 105, in __init__
    with h5py.File(map_fname, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/lib/python3.11/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = '/anaconda3/lib/python3.11/site-packages/dustmaps/data/bayestar/bayestar2019.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

I tried manually downloading this file via the [dustmaps](https://dustmaps.readthedocs.io/en/latest/index.html) package, but it raises a JSONDecodeError (see this GitHub [issue](https://github.com/gregreen/dustmaps/issues/54) for more details).

Is there a way to bypass this without waiting for the issue to be resolved by `dustmaps`?

**Comment by kemasuda** [comment]
Well, the answer will depend on the specifics of your project. But if the star is relatively nearby (say <100pc) and off the galactic plane, just setting ak, ak_err = 0, 0 might not make a big difference. See also [this](https://github.com/kemasuda/jaxstar/blob/main/demos/isochrone%20fitting%20example.ipynb) for what this code does minimally. It's up to the users to prepare appropriate values/uncertainties for magnitudes, teff, ...  etc. I may be able to make suggestions depending on what you work on but again that will be out of the scope of this code.
